parse_config:
  zmk_remove_keycode_prefix: []
  raw_binding_map:
    "&kp LS(DEL)": "Cut"
    "&kp LC(INS)": "Copy"
    "&kp LS(INS)": "Paste"
    "&kp K_UNDO": "Undo"
    "&kp K_AGAIN": "Again"
    "&bootloader": "Boot"
    "&u_bootloader": "Boot"
    "U_BOOT": "Boot"
    "&sys_reset": "Reset"
    '&caps_word': "Cps Wrd"
    '&mkp MB1': "Left Button"
    '&mkp MB2': "Right Button"
    '&mkp MB3': "Middle Button"
    '&u_to_U_BASE': "To Base"
    '&u_to_U_EXTRA': "To Extra" 
    '&u_to_U_TAP': "To Tap"
    '&u_to_U_BUTTON': "To Button"
    '&u_to_U_NAV': "To Nav"
    '&u_to_U_MOUSE': "To Mouse"
    '&u_to_U_MEDIA': "To Media"
    '&u_to_U_NUM': "To Num"
    '&u_to_U_SYM': "To Sym"
    '&u_to_U_FUN': "To Fun"
    "&bt BT_CLR": "BT Clr"
    "&bt BT_SEL 0": "BT 0"
    "&bt BT_SEL 1": "BT 1"
    "&bt BT_SEL 2": "BT 2"
    "&bt BT_SEL 3": "BT 3"
    "&bt BT_SEL 4": "BT 4"
    "&u_bt_sel_0": "BT 0"
    "&u_bt_sel_1": "BT 1"
    "&u_bt_sel_2": "BT 2"
    "&u_bt_sel_3": "BT 3"
    "&u_bt_sel_4": "BT 4"
    "&out OUT_USB": "Out USB"
    "&out OUT_BLE": "Out BLE"
    "&out OUT_TOG": "Out Tog"
    "&u_out_tog": "Out Tog"
    "&rgb_ug RGB_TOG": "RGB Tog"
    "&rgb_ug RGB_ON": "RGB On"
    "&rgb_ug RGB_OFF": "RGB Off"
    "&ext_power EP_ON": "EP On"
    "&ext_power EP_OFF": "EP Off"
    "&ext_power EP_TOG": "EP Tog"
  layer_legend_map:
    U_BASE: "Base"
    U_EXTRA: "Extra"
    U_TAP: "Tap"
    U_BUTTON: "Button"
    U_NAV: "Nav"
    U_MOUSE: "Mouse"
    U_MEDIA: "Media"
    U_NUM: "Num"
    U_SYM: "Sym"
    U_FUN: "Fun"

draw_config:
  key_rx: 6.0
  key_ry: 6.0
  key_w: 60.0
  key_h: 60.0
  n_columns: 2  # 2-column layout for reduced height
