draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: true
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: ''
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&kp LS(DEL)": "Cut"
    "&kp LC(INS)": "Copy"
    "&kp LS(INS)": "Paste"
    "&kp K_UNDO": "Undo"
    "&kp K_AGAIN": "Again"
    "&bootloader": "Boot"
    "&u_bootloader": "Boot"
    "U_BOOT": "Boot"
    "&sys_reset": "Reset"
    '&caps_word': "Cps Wrd"
    '&mkp MB1': "Left Button"
    '&mkp MB2': "Right Button"
    '&mkp MB3': "Middle Button"
    '&u_to_U_BASE': "To Base"
    '&u_to_U_EXTRA': "To Extra" 
    '&u_to_U_TAP': "To Tap"
    '&u_to_U_BUTTON': "To Button"
    '&u_to_U_NAV': "To Nav"
    '&u_to_U_MOUSE': "To Mouse"
    '&u_to_U_MEDIA': "To Media"
    '&u_to_U_NUM': "To Num"
    '&u_to_U_SYM': "To Sym"
    '&u_to_U_FUN': "To Fun"
    "&bt BT_CLR": "BT Clr"
    "&bt BT_SEL 0": "BT 0"
    "&bt BT_SEL 1": "BT 1"
    "&bt BT_SEL 2": "BT 2"
    "&bt BT_SEL 3": "BT 3"
    "&bt BT_SEL 4": "BT 4"
    "&u_bt_sel_0": "BT 0"
    "&u_bt_sel_1": "BT 1"
    "&u_bt_sel_2": "BT 2"
    "&u_bt_sel_3": "BT 3"
    "&u_bt_sel_4": "BT 4"
    "&out OUT_USB": "Out USB"
    "&out OUT_BLE": "Out BLE"
    "&out OUT_TOG": "Out Tog"
    "&u_out_tog": "Out Tog"
    "&rgb_ug RGB_TOG": "RGB Tog"
    "&rgb_ug RGB_ON": "RGB On"
    "&rgb_ug RGB_OFF": "RGB Off"
    "&ext_power EP_ON": "EP On"
    "&ext_power EP_OFF": "EP Off"
    "&ext_power EP_TOG": "EP Tog"
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map:
    U_BASE: "Base"
    U_EXTRA: "Extra"
    U_TAP: "Tap"
    U_BUTTON: "Button"
    U_NAV: "Nav"
    U_MOUSE: "Mouse"
    U_MEDIA: "Media"
    U_NUM: "Num"
    U_SYM: "Sym"
    U_FUN: "Fun"
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
